stages:
- name: Deploy db
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-mssql-server
      version: 0.1.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        # Always true in this time
        db.gui: true
        auth.saPassword: templatePassword
        image.tag: 2019-CU10-ubuntu-20.04
        # Common project info
        git.url: ${CICD_GIT_URL}
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
    when:
      branch:
        include:
          - master
