stages:
- name: Integration--initial pipeline
  iiidevops: initial-pipeline
  steps:
  - envFrom:
    - sourceKey: api-origin
      sourceName: nexus
      targetKey: api_origin
    runScriptConfig:
      image: iiiorg/rancher-cli:v2.4.6
      shellScript: curl --location -s --request POST ${api_origin}/rancher/delete_app
        --form project_name=${CICD_GIT_REPO_NAME} --form branch_name=${CICD_GIT_BRANCH}
        && curl --location -s --request POST ${api_origin}/project/issues_commit_by_name
        --form project_name=${CICD_GIT_REPO_NAME}
- name: Deploy--DB(MS-SQL)
  iiidevops: deployed-environments
  steps:
  - applyAppConfig:
      answers:
        db.gui: true
        auth.saPassword: templatePassword123!
        image.tag: 2019-CU10-ubuntu-20.04
        git.url: ${CICD_GIT_URL}
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
      catalogTemplate: cattle-global-data:iii-dev-charts3-mssql-server
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
      targetNamespace: ${CICD_GIT_REPO_NAME}
      version: 0.1.0
  when:
    branch:
      include:
      - master

